server:
  port: 7002

eureka:
  instance:
    hostname: localhost
    status-page-url: http://localhost:7002/index
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/  #注册中心的地址

spring:
  application:
    name: eureka-client  #服务的名字

