server:
  port: 7006

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # 配置git仓库的地址
          uri: https://github.com/Delena1988/spring-cloud-config-repo
          # git仓库地址下的相对地址，可以配置多个，用,分割。
          search-paths: /**
          # git仓库的账号（私有库必填）
          username:
          # git仓库的密码（私有库必填）
          password:
      # 配置git仓库的分支
      label: master
eureka:
  client:
    serviceUrl:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://localhost:7001/eureka/